### ISSUE TITLE
Consider UUIDv6?

### ISSUE THREAD

**Issue by mathiasbynens** [WICG/uuid#25]
The explainer says:

> Initially, the only
version of UUID supported will be the [version 4 "Algorithm for Creating a UUID from Truly Random or Pseudo-Random Numbers"](https://tools.ietf.org/html/rfc4122#section-4.4).

I just wanted to double-check that the authors are aware of the ongoing IETF work on UUIDv6, since it _sounds_ like a minor change we might as well include in this proposal as well (possibly _instead_ of v4?). From <https://mailarchive.ietf.org/arch/msg/dispatch/fqV3-FU7CbhshRFPRpILwIncXMw/>:

> UUIDv6 aims to be the easiest to implement for those already utilizing RFC 4122 UUIDv1 and keeps everything except the timestamp as-is.

(Disclaimer: I'm not at all familiar with this IETF work, I just wanted to make sure this is on y'alls radar in case it wasn't already.)

**Comment by ctavan** [comment]
As far as I understand the `v6+` efforts aim at fixing the flaws ([examples]( https://github.com/tc39/proposal-uuid#arent-v1-uuids-better-because-they-are-guaranteed-to-be-unique)) that time-based `v1` UUIDs had.

For the time being we intentionally DID NOT plan to provide time-based UUIDs due to the reasons outlined in [the analysis of real world UUID usage](https://github.com/tc39/proposal-uuid/blob/master/analysis/README.md#analysis-of-uuid-usage-in-github-bigquery-dataset).

That said there’s nothing preventing us to add support for other UUID versions in the future. However, so far the aim has been to focus on the parts of the spec that are most useful/used, not to provide a _complete_ implementation.

**Comment by broofa** [comment]
Glad to see they're switching to [pseudo] random data for the `node` field in the new UUID versions.  🎉
